type: object
name: HubConfig
properties:
  port:
    type: integer
    description: The port on which the server will listen for incoming requests.
    default: 8080
  enable_proxy:
    type: boolean
    description: If true, the server will accept requests from a proxy server.
    default: true
  engine_port_min:
    type: integer
    description: The minimum port number that the server will use to communicate with engines.
    default: 8081
  engine_port_max:
    type: integer
    description: The maximum port number that the server will use to communicate with engines.
    default: 10000
  on_start:
    patternProperties:
      "^.*$":
        type: object
        properties:
          quant:
            type: string
          engine:
            type: string
          context_sizes:
            type: array
            items:
              type: integer
  engines:
    type: object
    description: A dictionary of engine configurations.
    patternProperties:
      "^[a-zA-Z0-9_-]+$":
        type: object
        properties:
          path:
            type: string
          arguments:
            type: string
          model_flag:
            type: string
          context_size_flag:
            type: string
          port_flag:
            type: string
          api_key_flag:
            type: string
          file_types:
            type: array
            items:
              type: string
